---
title: "Highlights"
author: "Eric Scheier"
date: "1/21/2021"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
is_final=FALSE
is_preview=TRUE#
is_draft=TRUE
set.seed(123)

knitr::opts_chunk$set(comment='##', 
                      collapse=ifelse(is_preview,TRUE,!is_draft),
                      echo=ifelse(is_preview,FALSE,is_draft),
                      eval=TRUE,
                      warning=ifelse(is_preview,FALSE,is_draft),
                      error=ifelse(is_preview,FALSE,is_draft),
                      results=ifelse(is_final,'hide',ifelse(is_preview,'hide','asis')),
                      fig.keep='all',
                      message=ifelse(is_preview,FALSE,is_draft),
                      include=ifelse(is_preview,TRUE,is_draft),
                      tidy=TRUE,
                      cache=FALSE,
                      fig.margin=FALSE,
                      fig.fullwidth = TRUE
                      )
```

```{r sources}
source("sources.R")
```

```{r parameters}
states <- "all" #c("ca","nc","sc") #
refresh <- FALSE
acs_version <- 2018
# geographic_scope <- "tract" #statecitycounty
```

```{r run-methods, cache=FALSE}
paper_methods(states=states,
              acs_version=acs_version,
              refresh=refresh)
```

```{r load-data}
states <- "all" #c("ca","nc","sc") #
# replica_sup <- get_replica_supplemental_dataset()
# states <- c("ca", "nc","sc") # c("nc","ca") #  "nc" #"all" #
# income_metric <- "ami68" #"fpl15" #
# geographic_scope <- "tract" #statecitycounty
# format <- "replica" # "lead" #
# refresh <- FALSE

income_metric <- "AMI" #"AMI" #"fpl15" #
geographic_scope <- "Census Tracts" #statecitycounty
load_format <- "very_clean" #replica #lead #raw
save_ext <- "csv"#"fst",#
save_format <- "very_clean" #"replica"

version_text <- as.character(acs_version)
if(acs_version==2016){
  version_text <- "sh"
}

base_file_name <- tolower(paste(income_metric,
                                geographic_scope,
                                version_text,
                                paste(states,collapse="_",sep=""), sep = "_"))
# paste0("data/clean_lead_",base_file_name,".",save_ext)

clean_data_ami <- read_csv(paste0("data/very_clean_data_",base_file_name,".csv"), guess_max = Inf)

income_metric <- "FPL"
base_file_name <- tolower(paste(income_metric,
                                geographic_scope,
                                version_text,
                                paste(states,collapse="_",sep=""), sep = "_"))
clean_data_fpl <- read_csv(paste0("data/very_clean_data_",base_file_name,".csv"), guess_max = Inf)

census_tracts_shp <- st_read("data/all_census_tracts.geojson")
replica_sup <- get_replica_supplemental_dataset()
```


```{r}
replica_sup$pct_african_american <- replica_sup$pop_african_american / replica_sup$pop_total

replica_sup$households <- (replica_sup$hu_own + replica_sup$hu_rent)

replica_sup$income_per_capita <- (replica_sup$hh_med_income * replica_sup$households) / replica_sup$pop_total

replica_sup$unemployment_rate <- replica_sup$p16_unempl / (replica_sup$p16_unempl + replica_sup$p16_employ)
```


```{r join_data}
tract_shp <- st_sf(left_join(census_tracts_shp, replica_sup, by=c("gisjoin")))
```


```{r chart_params}
#chart_title <- "Household Economic Return on Energy Spending"
chart_title <- "Median Net Energy Return"
chart_subtitle <- "Per Census Tract"

group_columns <- NULL #"income_bracket")#in_poverty
                   #"primary_heating_fuel"

metric_name <- "ner" #"energy_burden" #"ner" #"dear" #"eroi"
metric_label <- "$/$"
metric_cutoff_level <- 9
metric_cutoff_label <- "9"

upper_quantile_view <- 1.0
lower_quantile_view <- 0.0
```

```{r grouped_weighted_metrics}
#data$GEOID <- sub('.', '', data$gisjoin)
group_columns <- c("geoid") #c("gisjoin") #
graph_data <- filter_graph_data(clean_data_ami, group_columns, metric_name)

gwm <- grouped_weighted_metrics(graph_data, 
                         group_columns, 
                         metric_name, 
                         metric_cutoff_level, 
                         upper_quantile_view=0.75, 
                         lower_quantile_view=0.25)
# head(gwm)
```

```{r select_area}
# remove HI and AK
# continental_shp <- tract_shp %>% filter(!(state_abbr %in% c("HI","AK", NA)))
# add utility cutout
county_long_name <- "Baltimore city"
county_shp <- tract_shp %>% filter(county_name %in% c(county_long_name))

county_water <- area_water(state = "MD",
                           county = county_long_name,
                           year = acs_version,
                           refresh = FALSE)

county_shp <- county_shp %>% st_difference(st_union(county_water))
```

```{r join_to_area}
map_data <- left_join(county_shp, gwm, by=c("geoid"))

clean_top_metrics <- grouped_weighted_metrics(graph_data %>% 
                                                filter(!(state_abbr %in% c("HI","AK", NA))), 
                         group_columns=NULL, 
                         metric_name, 
                         metric_cutoff_level, 
                         upper_quantile_view=1, 
                         lower_quantile_view=0)
# head(clean_top_metrics)

```

```{r continental_map, out.width="100%", fig.cap="Map of the median net earned income per secondary energy expenditure for each census tract in the continental United States."}
# figure_name <- "choropleth_map"
# figure_file <- paste0("figures/",figure_name,".png")
# if(!file.exists(figure_file) || refresh){
choropleth_chart <- choropleth_map(
    clean_data=map_data,
    group_columns,
    metric_name,
    metric_label,
    metric_cutoff_level,
    metric_cutoff_label,
    upper_quantile_view,
    lower_quantile_view,
    chart_title,
    chart_subtitle,
    weighted_metrics=clean_top_metrics)
  # ggsave(figure_file, plot=choropleth_chart)
# }
choropleth_chart
```

```{r}
#chart_title <- "Household Economic Return on Energy Spending"
chart_title <- "Percent African American"
chart_subtitle <- "Per Census Tract"

group_columns <- c("geoid") #"income_bracket")#in_poverty
                   #"primary_heating_fuel"

metric_name <- "pct_african_american" #"energy_burden" #"ner" #"dear" #"eroi"
metric_label <- "%"
metric_cutoff_level <- median(county_shp$pct_african_american, na.rm = T)
metric_cutoff_label <- ""

upper_quantile_view <- 1.0
lower_quantile_view <- 0.0

graph_data <- filter_graph_data(county_shp, group_columns, metric_name)

gwm <- grouped_weighted_metrics(graph_data,
                         group_columns,
                         metric_name,
                         metric_cutoff_level,
                         upper_quantile_view=1.0,#0.75,
                         lower_quantile_view=0.0)#0.25)

gwm <- graph_data[,c("geoid", metric_name)]
gwm <- rename(gwm, metric_median = !!sym(metric_name))

map_data <- left_join(graph_data, st_drop_geometry(gwm), by=c("geoid"))

clean_top_metrics <- grouped_weighted_metrics(replica_sup %>% 
                                                filter(!(state_abbr %in% c("HI","AK", NA))),
                                              group_columns=NULL,
                                              metric_name,
                                              metric_cutoff_level,
                                              upper_quantile_view=1.0,
                                              lower_quantile_view=0.0)

choropleth_chart <- choropleth_map(
    clean_data=map_data,
    group_columns,
    metric_name,
    metric_label,
    metric_cutoff_level,
    metric_cutoff_label,
    upper_quantile_view,
    lower_quantile_view,
    chart_title,
    chart_subtitle,
    weighted_metrics=clean_top_metrics)
  # ggsave(figure_file, plot=choropleth_chart)
# }
choropleth_chart
```
```{r}
#chart_title <- "Household Economic Return on Energy Spending"
chart_title <- "Per Capita Income"
chart_subtitle <- "Per Census Tract"

group_columns <- c("geoid") #"income_bracket")#in_poverty
                   #"primary_heating_fuel"

metric_name <- "income_per_capita" #"energy_burden" #"ner" #"dear" #"eroi"
metric_label <- "$"
metric_cutoff_level <- median(county_shp$income_per_capita, na.rm = T)
metric_cutoff_label <- ""

upper_quantile_view <- 1.0
lower_quantile_view <- 0.0

graph_data <- filter_graph_data(county_shp, group_columns, metric_name)

gwm <- grouped_weighted_metrics(graph_data,
                         group_columns,
                         metric_name,
                         metric_cutoff_level,
                         upper_quantile_view=1.0,#0.75,
                         lower_quantile_view=0.0)#0.25)

gwm <- graph_data[,c("geoid", metric_name)]
gwm <- rename(gwm, metric_median = !!sym(metric_name))

map_data <- left_join(graph_data, st_drop_geometry(gwm), by=c("geoid"))

clean_top_metrics <- grouped_weighted_metrics(replica_sup %>% 
                                                filter(!(state_abbr %in% c("HI","AK", NA))),
                                              group_columns=NULL,
                                              metric_name,
                                              metric_cutoff_level,
                                              upper_quantile_view=1.0,
                                              lower_quantile_view=0.0)

choropleth_chart <- choropleth_map(
    clean_data=map_data,
    group_columns,
    metric_name,
    metric_label,
    metric_cutoff_level,
    metric_cutoff_label,
    upper_quantile_view,
    lower_quantile_view,
    chart_title,
    chart_subtitle,
    weighted_metrics=clean_top_metrics)
  # ggsave(figure_file, plot=choropleth_chart)
# }
choropleth_chart
```


```{r}
#chart_title <- "Household Economic Return on Energy Spending"
chart_title <- "Unemployment Rate"
chart_subtitle <- "Per Census Tract"

group_columns <- c("geoid") #"income_bracket")#in_poverty
                   #"primary_heating_fuel"

metric_name <- "unemployment_rate" #"energy_burden" #"ner" #"dear" #"eroi"
metric_label <- "%"
metric_cutoff_level <- median(county_shp$unemployment_rate, na.rm = T)
metric_cutoff_label <- ""

upper_quantile_view <- 1.0
lower_quantile_view <- 0.0

graph_data <- filter_graph_data(county_shp, group_columns, metric_name)

gwm <- grouped_weighted_metrics(graph_data,
                         group_columns,
                         metric_name,
                         metric_cutoff_level,
                         upper_quantile_view=1.0,#0.75,
                         lower_quantile_view=0.0)#0.25)

gwm <- graph_data[,c("geoid", metric_name)]
gwm <- rename(gwm, metric_median = !!sym(metric_name))

map_data <- left_join(graph_data, st_drop_geometry(gwm), by=c("geoid"))

clean_top_metrics <- grouped_weighted_metrics(replica_sup %>% 
                                                filter(!(state_abbr %in% c("HI","AK", NA))),
                                              group_columns=NULL,
                                              metric_name,
                                              metric_cutoff_level,
                                              upper_quantile_view=1.0,
                                              lower_quantile_view=0.0)

choropleth_chart <- choropleth_map(
    clean_data=map_data,
    group_columns,
    metric_name,
    metric_label,
    metric_cutoff_level,
    metric_cutoff_label,
    upper_quantile_view,
    lower_quantile_view,
    chart_title,
    chart_subtitle,
    weighted_metrics=clean_top_metrics)
  # ggsave(figure_file, plot=choropleth_chart)
# }
choropleth_chart
```