source("libraries.R")
source("ratios.R")
source("helpers.R")
source("figures.R")
source("replica_munging.R")
source("lead_munging.R")
source("shapefile_munging.R")
source("egrid_munging.R")
source("methods.R")

source("comparison_table.R")